### ISSUE TITLE
Max density is too low to be realistic for city scenarios

### ISSUE THREAD

**Issue by xaroth8088** [ZehMatt/7dtd-WalkerSim2#4]
With acknowledgement that yes, the game may not run well at all with a higher setting, a population density of 400 / km^2 is only that of a typical suburb.  Densities for cities in the US tend to be somewhere around 2,000 to 3,000 / km^2.

Consider lifting the hard limit on the number, and instead display a warning when the value is higher than 400.

**Comment by ZehMatt** [comment]
Fine, I'll raise the limit to 1 million agents and max density of 4000. Be warned that it will affect the performance with such large numbers.
