### ISSUE TITLE
[Feature Request] 1.2 support

### ISSUE THREAD

**Issue by xaroth8088** [ZehMatt/7dtd-WalkerSim2#9]
I attempted to make my own build against `latest_experimental`, but they've changed an API it would seem.  Here's the relevant error message:

`D:\a\7dtd-WalkerSim2\7dtd-WalkerSim2\Mod\SpawnManager.cs(89,58): error CS1061: 'BiomeSpawnEntityGroupData' does not contain a definition for 'entityGroupRefName' and no accessible extension method 'entityGroupRefName' accepting a first argument of type 'BiomeSpawnEntityGroupData' could be found (are you missing a using directive or an assembly reference?) [D:\a\7dtd-WalkerSim2\7dtd-WalkerSim2\Mod\Mod.csproj]
`

Full build log here: https://github.com/xaroth8088/7dtd-WalkerSim2/actions/runs/12191745465/job/34011167947

**Comment by ZehMatt** [comment]
Will have to look into it.

**Comment by ZehMatt** [comment]
1.2 is supported now.
